global using ASC.Api.Core;
global using ASC.Api.Core.Extensions;
global using ASC.Common;
global using ASC.Common.Caching;
global using ASC.Common.Utils;
global using ASC.Core.Common.EF;
global using ASC.Mail.Configuration;
global using ASC.Mail.Core.Dao.Context;
global using ASC.Mail.Core.Engine;
global using ASC.Mail.Core.Extensions;
global using ASC.Mail.Server.Core.Dao;
global using ASC.Mail.Watchdog.Service;
global using CommandLine;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Hosting.WindowsServices;
global using Microsoft.Extensions.Logging;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
