// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace ASC.Mail.Core.Dao.Entities;

public partial class CrmContactInfo : BaseEntity
{
    public int Id { get; set; }
    public string Data { get; set; }
    public int Category { get; set; }
    public int TenantId { get; set; }
    public sbyte IsPrimary { get; set; }
    public int ContactId { get; set; }
    public int Type { get; set; }
    public DateTime? LastModifedOn { get; set; } 
    public string LastModifedBy { get; set; }

    public override object[] GetKeys() => new object[] { Id };
}
public static class CrmContactInfoExtension
{
    public static ModelBuilder AddCrmContactInfo(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CrmContactInfo>(entity =>
        {
            entity.ToTable("crm_contact_info");

            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("int(10)")
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.LastModifedOn)
                .HasDatabaseName("last_modifed_on");

            entity.HasIndex(e => new { e.TenantId, e.ContactId })
                .HasDatabaseName("IX_Contact");

            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnName("data")
                .HasColumnType("text")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.LastModifedBy)
                .HasColumnName("last_modifed_by")
                .HasColumnType("char(38)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Category)
                .HasColumnName("category")
                .HasColumnType("int(255)");

            entity.Property(e => e.TenantId)
                .HasColumnName("tenant_id")
                .HasColumnType("int(255)");

            entity.Property(e => e.IsPrimary)
                .HasColumnName("is_primary")
                .HasColumnType("tinyint(4)");

            entity.Property(e => e.ContactId)
                .HasColumnName("contact_id")
                .HasColumnType("int(11)");

            entity.Property(e => e.Type)
                .HasColumnName("type")
                .HasColumnType("int(255)");

            entity.Property(e => e.LastModifedOn)
                .HasColumnName("last_modifed_on")
                .HasColumnType("datetime");
        });

        return modelBuilder;
    }
}
