// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class CrmTag : BaseEntity
{
    public int Id { get; set; }
    public string Title { get; set; }
    public int IdTenant { get; set; }
    public int EntityType { get; set; }

    public override object[] GetKeys() => new object[] { Id };
}

public static class CrmTagExtension
{
    public static ModelBuilder AddCrmTag(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CrmTag>(entity =>
        {
            entity.ToTable("crm_tag");

            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("int(11)")
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => new { e.IdTenant })
                .HasDatabaseName("tenant_id");

            entity.Property(e => e.Title)
                .HasColumnName("title")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.EntityType)
                .HasColumnName("entity_type")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdTenant)
                .HasColumnName("tenant_id")
                .HasColumnType("int(11)");
        });

        return modelBuilder;
    }
}
