// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Common;
using ASC.Core.Common.EF;
using ASC.ElasticSearch;
using ASC.ElasticSearch.Core;

using Microsoft.EntityFrameworkCore;

using Nest;

using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ASC.Mail.Core.Dao.Entities
{
    [Transient]
    [ElasticsearchType(RelationName = Tables.Contact)]
    public partial class MailContact : BaseEntity, ISearchItem
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int TenantId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public bool HasPhoto { get; set; }
        public DateTime LastModified { get; set; }

        [Nested]
        public ICollection<MailContactInfo> InfoList { get; set; }

        [Ignore]
        public string IndexName
        {
            get => Tables.Contact;
        }

        public override object[] GetKeys()
        {
            return new object[] { Id };
        }

        public Expression<Func<ISearchItem, object[]>> GetSearchContentFields(SearchSettingsHelper searchSettings)
        {
            return (a) => new[] { Name, Address };
        }
    }

    public static class MailContactExtension
    {
        public static ModelBuilder AddMailContact(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailContact>(entity =>
            {
                entity.ToTable("mail_contacts");

                entity.Ignore(e => e.InfoList);
                entity.Ignore(e => e.IndexName);

                entity.HasIndex(e => e.LastModified)
                    .HasDatabaseName("last_modified");

                entity.HasKey(e => e.Id)
                    .HasName("PRIMARY");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("int(11) unsigned")
                    .ValueGeneratedOnAdd();

                entity.Property(e => e.TenantId)
                    .HasColumnName("tenant")
                    .HasColumnType("int(11)");

                entity.HasIndex(e => new { e.TenantId, e.IdUser, e.Address })
                    .HasDatabaseName("tenant_id_user_name_address");

                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasColumnName("address")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.Description)
                    .HasColumnName("description")
                    .HasColumnType("varchar(100)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.IdUser)
                    .IsRequired()
                    .HasColumnName("id_user")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.LastModified)
                    .HasColumnName("last_modified")
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.Type)
                    .HasColumnName("type")
                    .HasColumnType("int(11)");

                entity.Property(e => e.HasPhoto)
                    .HasColumnName("has_photo");


                entity.HasMany(m => m.InfoList)
                    .WithOne(a => a.Contact)
                    .HasForeignKey(a => a.IdContact);
            });

            return modelBuilder;
        }
    }
}