// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

[ElasticsearchType(RelationName = Tables.UserFolder)]
public partial class MailUserFolderXMail : BaseEntity
{
    [Nest.PropertyName("id")]
    public int IdFolder { get; set; }

    [Nest.PropertyName("tenantId")]
    public int Tenant { get; set; }

    [Nest.PropertyName("lastModifiedOn")]
    public DateTime TimeCreated { get; set; }

    [Ignore]
    public string IdUser { get; set; }

    [Ignore]
    public int IdMail { get; set; }

    public override object[] GetKeys() => new object[] { Tenant, IdUser, IdMail };
}

public static class MailUserFolderXMailExtension
{
    public static ModelBuilderWrapper AddMailUserFolderXMail(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailUserFolderXMail, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailUserFolderXMail(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailUserFolderXMail>(entity =>
        {
            entity.ToTable("mail_user_folder_x_mail");

            entity.HasKey(e => new { e.Tenant, e.IdUser, e.IdMail, e.IdFolder })
                .HasName("PRIMARY");

            entity.HasIndex(e => e.IdFolder)
                .HasDatabaseName("id_tag");

            entity.HasIndex(e => e.IdMail)
                .HasDatabaseName("id_mail");

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdMail)
                .HasColumnName("id_mail")
                .HasColumnType("int(11) unsigned");

            entity.Property(e => e.IdFolder)
                .HasColumnName("id_folder")
                .HasColumnType("int(11) unsigned");

            entity.Property(e => e.IdUser)
                .HasColumnName("id_user")
                .HasColumnType("varchar(38)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.TimeCreated)
                .HasColumnName("time_created")
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .ValueGeneratedOnAddOrUpdate();
        });
    }
}
