// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailTagAddresses : BaseEntity
{
    public uint IdTag { get; set; }
    public string Address { get; set; }
    public int Tenant { get; set; }

    public override object[] GetKeys() => new object[] { IdTag, Address, Tenant };
}

public static class MailTagAddressesExtension
{
    public static ModelBuilder AddMailTagAddresses(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailTagAddresses>(entity =>
        {
            entity.ToTable("mail_tag_addresses");

            entity.HasKey(e => new { e.IdTag, e.Address, e.Tenant })
                .HasName("PRIMARY");

            entity.Property(e => e.Address)
                .HasColumnName("address")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.IdTag)
                .HasColumnName("id_tag")
                .HasColumnType("int(11) unsigned");

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(11)");
        });

        return modelBuilder;
    }
}
