// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;
using Microsoft.EntityFrameworkCore;
using System;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailUserFolderXMail : BaseEntity
    {
        public int Tenant { get; set; }
        public string IdUser { get; set; }
        public int IdMail { get; set; }
        public int IdFolder { get; set; }
        public DateTime TimeCreated { get; set; }

        public override object[] GetKeys() => new object[] { Tenant, IdUser, IdMail };
    }

    public static class MailUserFolderXMailExtension
    {
        public static ModelBuilder AddMailUserFolderXMail(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailUserFolderXMail>(entity =>
            {
                entity.ToTable("mail_user_folder_x_mail");

                entity.HasKey(e => new { e.Tenant, e.IdUser, e.IdMail, e.IdFolder })
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.IdFolder)
                    .HasDatabaseName("id_tag");

                entity.HasIndex(e => e.IdMail)
                    .HasDatabaseName("id_mail");

                entity.Property(e => e.Tenant)
                    .HasColumnName("tenant")
                    .HasColumnType("int(11)");

                entity.Property(e => e.IdMail)
                    .HasColumnName("id_mail")
                    .HasColumnType("int(11) unsigned");

                entity.Property(e => e.IdFolder)
                    .HasColumnName("id_folder")
                    .HasColumnType("int(11) unsigned");

                entity.Property(e => e.IdUser)
                    .HasColumnName("id_user")
                    .HasColumnType("varchar(38)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.TimeCreated)
                    .HasColumnName("time_created")
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP")
                    .ValueGeneratedOnAddOrUpdate();
            });

            return modelBuilder;
        }
    }
}