// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailServerServerXTenant : BaseEntity
{
    public int IdTenant { get; set; }
    public int IdServer { get; set; }

    public override object[] GetKeys() => new object[] { IdTenant, IdServer };
}

public static class MailServerServerXTenantExtension
{
    public static ModelBuilderWrapper AddMailServerServerXTenant(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailServerServerXTenant, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailServerServerXTenant(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailServerServerXTenant>(entity =>
        {
            entity.ToTable("mail_server_server_x_tenant");

            entity.HasKey(e => new { e.IdTenant, e.IdServer })
                .HasName("PRIMARY");

            entity.Property(e => e.IdTenant)
                .HasColumnName("id_tenant")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdServer)
                .HasColumnName("id_server")
                .HasColumnType("int(11)");
        });
    }
}
