// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailServerDomain : BaseEntity
{
    public int Id { get; set; }
    public int Tenant { get; set; }
    public string Name { get; set; }
    public bool IsVerified { get; set; }
    public DateTime DateAdded { get; set; }        
    public DateTime DateChecked { get; set; }

    public override object[] GetKeys() => new object[] { Id };
}

public static class MailServerDomainExtension
{
    public static ModelBuilder AddMailServerDomain(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailServerDomain>(entity =>
        {
            entity.ToTable("mail_server_domain");

            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("int(11)")
                .ValueGeneratedOnAdd();

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(11)");

            entity.HasIndex(e => e.DateChecked)
                .HasDatabaseName("date_checked");

            entity.HasIndex(e => e.Name)
                .HasDatabaseName("name")
                .IsUnique();

            entity.HasIndex(e => e.Tenant)
                .HasDatabaseName("tenant");

            entity.Property(e => e.DateChecked)
                .HasColumnName("date_checked")
                .HasColumnType("datetime")
                .HasDefaultValueSql("'1975-01-01 00:00:00'");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.IsVerified)
                .HasColumnName("is_verified")
                .HasColumnType("int(10)");

            entity.Property(e => e.DateAdded)
                .HasColumnName("date_added")
                .HasColumnType("datetime");
        });

        return modelBuilder;
    }
}
