// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailPopUnorderedDomain : BaseEntity
{
    public string Server { get; set; }

    public override object[] GetKeys() => new object[] { Server };
}

public static class MailPopUnorderedDomainExtension
{
    public static ModelBuilderWrapper AddMailPopUnorderedDomain(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailPopUnorderedDomain, Provider.MySql);

        return modelBuilder;
    }
    public static void MySqlAddMailPopUnorderedDomain(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailPopUnorderedDomain>(entity =>
        {
            entity.ToTable("mail_pop_unordered_domain");

            entity.HasKey(e => e.Server)
                .HasName("PRIMARY");

            entity.Property(e => e.Server)
                .HasColumnName("server")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");
        });
    }
}
