// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using ASC.Core.Common.EF.Model;
using ASC.Mail.Enums;
using Microsoft.EntityFrameworkCore;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailAlert
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }

        [Column("tenant", TypeName = "int(11)")]
        public int Tenant { get; set; }

        [Required]
        [Column("id_user", TypeName = "varchar(255)")]
        public string IdUser { get; set; }

        [Column("id_mailbox", TypeName = "int(11)")]
        public int IdMailbox { get; set; }

        [Column("type", TypeName = "int(11)")]
        public MailAlertTypes Type { get; set; }

        [Column("data", TypeName = "mediumtext")]
        public string Data { get; set; }
    }

    public static class MailAlertExtension
    {
        public static ModelBuilder AddMailAlert(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailAlert>(entity =>
            {
                entity.ToTable("mail_alerts");

                entity.HasKey(e => e.Id).HasName("PRIMARY");

                entity.Property(e => e.Tenant).HasColumnName("tenant");

                entity.HasIndex(e => new { e.Tenant, e.IdUser, e.IdMailbox, e.Type })
                    .HasDatabaseName("tenant_id_user_id_mailbox_type");

                entity.Property(e => e.Data)
                .HasColumnName("data")
                .HasColumnType("mediumtext")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.IdMailbox).HasDefaultValueSql("'-1'");

                entity.Property(e => e.IdUser)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}