// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;

using Microsoft.EntityFrameworkCore;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailChainXCrmEntity : BaseEntity
    {
        public int IdTenant { get; set; }
        public int IdMailbox { get; set; }
        public int EntityId { get; set; }
        public int EntityType { get; set; }
        public string IdChain { get; set; }

        public override object[] GetKeys() => new object[] { IdTenant, IdMailbox, IdChain, EntityId, EntityType };
    }

    public static class MailChainXCrmEntityExtension
    {
        public static ModelBuilder AddMailChainXCrmEntity(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailChainXCrmEntity>(entity =>
            {
                entity.ToTable("mail_chain_x_crm_entity");

                entity.HasKey(e => new { e.IdTenant, e.IdMailbox, e.IdChain, e.EntityId, e.EntityType })
                    .HasName("PRIMARY");

                entity.Property(e => e.IdTenant)
                    .HasColumnName("id_mailbox")
                    .HasColumnType("int(11)");

                entity.Property(e => e.IdMailbox)
                    .HasColumnName("id_tenant")
                    .HasColumnType("int(11)");

                entity.Property(e => e.EntityId)
                    .HasColumnName("entity_id")
                    .HasColumnType("int(11)");

                entity.Property(e => e.EntityType)
                    .HasColumnName("entity_type")
                    .HasColumnType("int(11)");

                entity.Property(e => e.IdChain)
                    .HasColumnName("id_chain")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}