// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;

using Microsoft.EntityFrameworkCore;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailMailboxSignature : BaseEntity
    {
        
        public int Tenant { get; set; }
        public int IdMailbox { get; set; }
        public string Html { get; set; }
        public bool IsActive { get; set; }

        public override object[] GetKeys() => new object[] { IdMailbox };
    }

    public static class MailMailboxSignatureExtension
    {
        public static ModelBuilder AddMailMailboxSignature(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailMailboxSignature>(entity =>
            {
                entity.ToTable("mail_mailbox_signature");

                entity.HasKey(e => e.IdMailbox)
                    .HasName("PRIMARY");

                entity.Property(e => e.IdMailbox)
                    .HasColumnName("id_mailbox")
                    .HasColumnType("int(11)");

                entity.HasIndex(e => e.Tenant)
                    .HasDatabaseName("tenant");

                entity.Property(e => e.Tenant)
                    .HasColumnName("tenant")
                    .HasColumnType("int(11)");

                entity.Property(e => e.Html)
                    .HasColumnName("html")
                    .HasColumnType("text")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.IsActive)
                    .HasColumnName("is_active")
                    .HasColumnType("tinyint(4)");
            });

            return modelBuilder;
        }
    }
}