// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailChain : BaseEntity
{
    public string Id { get; set; }
    public int IdMailbox { get; set; }
    public int Tenant { get; set; }
    public string IdUser { get; set; }
    public int Folder { get; set; }
    public int Length { get; set; }
    public bool Unread { get; set; }
    public bool HasAttachments { get; set; }
    public bool Importance { get; set; }
    public string Tags { get; set; }        
    public sbyte IsCrmChain { get; set; }

    public override object[] GetKeys() => new object[] { Tenant, IdUser, Id, IdMailbox, Folder };
}

public static class MailChainExtension
{
    public static ModelBuilder AddMailChain(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailChain>(entity =>
        {
            entity.ToTable("mail_chain");

            entity.HasKey(e => new { e.Tenant, e.IdUser, e.Id, e.IdMailbox, e.Folder })
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.IdUser)
                .HasColumnName("id_user")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(10) unsigned");

            entity.Property(e => e.IdMailbox)
                .HasColumnName("id_mailbox")
                .HasColumnType("int(10) unsigned");

            entity.Property(e => e.Folder)
                .HasColumnName("folder")
                .HasColumnType("int(10) unsigned");

            entity.Property(e => e.Length)
                .HasColumnName("length")
                .HasColumnType("int(10) unsigned");

            entity.Property(e => e.Unread)
                .HasColumnName("unread")
                .HasColumnType("tinyint(1) unsigned");

            entity.Property(e => e.HasAttachments)
                .HasColumnName("has_attachments")
                .HasColumnType("tinyint(1) unsigned");

            entity.Property(e => e.Importance)
                .HasColumnName("importance")
                .HasColumnType("tinyint(1) unsigned");

            entity.Property(e => e.Tags)
                .IsRequired()
                .HasColumnName("tags")
                .HasColumnType("text")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.IsCrmChain)
                .HasColumnName("is_crm_chain")
                .HasColumnType("tinyint(4)");
        });

        return modelBuilder;
    }
}
