// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

[ElasticsearchType(RelationName = Tables.Tag)]
public partial class MailTagMail : BaseEntity
{
    [Nest.PropertyName("id")]
    public int IdTag { get; set; }

    [Nest.PropertyName("tenantId")]
    public int Tenant { get; set; }

    [Nest.PropertyName("lastModifiedOn")]
    public DateTime TimeCreated { get; set; }

    [Ignore]
    public string IdUser { get; set; }

    [Ignore]
    public int IdMail { get; set; }

    public override object[] GetKeys() => new object[] { Tenant, IdUser, IdMail, IdTag };
}

public static class MailTagMailExtension
{
    public static ModelBuilderWrapper AddMailTagMail(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailTagMail, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailTagMail(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailTagMail>(entity =>
        {
            entity.ToTable("mail_tag_mail");

            entity.HasKey(e => new { e.Tenant, e.IdUser, e.IdMail, e.IdTag })
                .HasName("PRIMARY");

            entity.HasIndex(e => e.IdMail)
                .HasDatabaseName("id_mail");

            entity.HasIndex(e => e.IdTag)
                .HasDatabaseName("id_tag");

            entity.Property(e => e.IdUser)
                .HasColumnName("id_user")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdMail)
                .HasColumnName("id_mail")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdTag)
                .HasColumnName("id_tag")
                .HasColumnType("int(11)");

            entity.Property(e => e.TimeCreated)
                .HasColumnName("time_created")
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
        });
    }
}
