// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;

using Microsoft.EntityFrameworkCore;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailServerMailGroupXMailServerAddress : BaseEntity
    {        
        public int IdAddress { get; set; }        
        public int IdMailGroup { get; set; }

        public override object[] GetKeys() => new object[] { IdAddress, IdMailGroup };
    }

    public static class MailServerMailGroupXMailServerAddressExtension
    {
        public static ModelBuilder AddMailServerMailGroupXMailServerAddress(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailServerMailGroupXMailServerAddress>(entity =>
            {
                entity.ToTable("mail_server_mail_group_x_mail_server_address");

                entity.HasKey(e => new { e.IdAddress, e.IdMailGroup })
                    .HasName("PRIMARY");

                entity.Property(e => e.IdAddress)
                    .HasColumnName("id_address")
                    .HasColumnType("int(11)");

                entity.Property(e => e.IdMailGroup)
                    .HasColumnName("id_mail_group")
                    .HasColumnType("int(11)");
            });

            return modelBuilder;
        }
    }
}