// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailUserFolderTree: BaseEntity
{        
    public int FolderId { get; set; }
    public int ParentId { get; set; }
    public uint Level { get; set; }

    public override object[] GetKeys() => new object[] { ParentId, FolderId };
}

public static class MailUserFolderTreeExtension
{
    public static ModelBuilderWrapper AddMailUserFolderTree(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailUserFolderTree, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailUserFolderTree(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailUserFolderTree>(entity =>
        {
            entity.ToTable("mail_user_folder_tree");

            entity.HasKey(e => new { e.ParentId, e.FolderId })
                .HasName("PRIMARY");

            entity.HasIndex(e => e.FolderId)
                .HasDatabaseName("folder_id");

            entity.Property(e => e.FolderId)
                .HasColumnName("folder_id")
                .HasColumnType("int(11) unsigned");

            entity.Property(e => e.ParentId)
                .HasColumnName("parent_id")
                .HasColumnType("int(11) unsigned");

            entity.Property(e => e.Level)
                .HasColumnName("level")
                .HasColumnType("int(11) unsigned");
        });
    }
}
