// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;

using Microsoft.EntityFrameworkCore;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailMailboxDomain : BaseEntity
    {
        public int Id { get; set; }
        public int IdProvider { get; set; }
        public string Name { get; set; }

        public override object[] GetKeys() => new object[] { Id };
    }

    public static class MailMailboxDomainExtension
    {
        public static ModelBuilder AddMailMailboxDomain(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailMailboxDomain>(entity =>
            {
                entity.ToTable("mail_mailbox_domain");

                entity.HasIndex(e => new { e.Name, e.IdProvider })
                    .HasDatabaseName("id_provider");

                entity.HasKey(e => e.Id)
                    .HasName("PRIMARY");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("int(11)")
                    .ValueGeneratedOnAdd();

                entity.Property(e => e.IdProvider)
                    .HasColumnName("id_provider")
                    .HasColumnType("int(11)");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            modelBuilder.Entity<MailMailboxDomain>().HasData(new MailMailboxDomain
            {
                Id = 924, IdProvider = 69, Name = "gmail.com"
            });

            return modelBuilder;
        }
    }
}