// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailImapFlags : BaseEntity
{
    public string Name { get; set; }        
    public int FolderId { get; set; }        
    public bool Skip { get; set; }

    public override object[] GetKeys()
    {
        return new object[] { Name };
    }
}

public static class MailImapFlagsExtension
{
    public static ModelBuilderWrapper AddMailImapFlags(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailImapFlags, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailImapFlags(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailImapFlags>(entity =>
        {
            entity.ToTable("mail_imap_flags");

            entity.HasKey(e => e.Name)
                .HasName("PRIMARY");

            entity.Property(e => e.Name)
                .HasColumnName("name")
                .HasColumnType("varchar(50)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.FolderId)
                .HasColumnName("folder_id")
                .HasColumnType("int(11)");

            entity.Property(e => e.Skip)
                .HasColumnName("skip")
                .HasColumnType("int(11)");
        });
    }
}
