// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    public partial class MailImapSpecialMailbox : BaseEntity
    {
        public string Server { get; set; }
        public string Name { get; set; }
        public int FolderId { get; set; }
        public bool Skip { get; set; }

        public override object[] GetKeys()
        {
            return new object[] { Server, Name };
        }
    }

    public static class MailImapSpecialMailboxExtension
    {
        public static ModelBuilder AddMailImapSpecialMailbox(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailImapSpecialMailbox>(entity =>
            {
                entity.ToTable("mail_imap_special_mailbox");

                entity.HasKey(e => new { e.Server, e.Name })
                    .HasName("PRIMARY");

                entity.Property(e => e.Server)
                    .HasColumnName("server")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasColumnType("varchar(255)")
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.FolderId)
                    .HasColumnName("folder_id")
                    .HasColumnType("int(11)");

                entity.Property(e => e.Skip)
                    .HasColumnName("skip")
                    .HasColumnType("int(11)");
            });

            return modelBuilder;
        }
    }
}