// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailServerServer : BaseEntity
{
    public int Id { get; set; }
    public string MxRecord { get; set; }
    public string ConnectionString { get; set; }
    public int ServerType { get; set; }
    public int SmtpSettingsId { get; set; }
    public int ImapSettingsId { get; set; }

    public override object[] GetKeys() => new object[] { Id };
}

public static class MailServerServerExtension
{
    public static ModelBuilderWrapper AddMailServerServer(this ModelBuilderWrapper modelBuilder)
    {
        modelBuilder
            .Add(MySqlAddMailServerServer, Provider.MySql);

        return modelBuilder;
    }

    public static void MySqlAddMailServerServer(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailServerServer>(entity =>
        {
            entity.ToTable("mail_server_server");

            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("int(11)")
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.ServerType)
                .HasDatabaseName("mail_server_server_type_server_type_fk_id");

            entity.Property(e => e.ServerType)
                .HasColumnName("server_type")
                .HasColumnType("int(11)");

            entity.Property(e => e.SmtpSettingsId)
                .HasColumnName("smtp_settings_id")
                .HasColumnType("int(11)");

            entity.Property(e => e.ImapSettingsId)
                .HasColumnName("imap_settings_id")
                .HasColumnType("int(11)");

            entity.Property(e => e.ConnectionString)
                .IsRequired()
                .HasColumnName("connection_string")
                .HasColumnType("text")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.MxRecord)
                .IsRequired()
                .HasColumnName("mx_record")
                .HasColumnType("varchar(128)")
                .HasDefaultValueSql("''")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");
        });
    }
}
