// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailDisplayImages : BaseEntity
{
    public int Tenant { get; set; }
    public string IdUser { get; set; }
    public string Address { get; set; }

    public override object[] GetKeys()
    {
        return new object[] { Tenant, IdUser, Address };
    }
}

public static class MailDisplayImagesExtension
{
    public static ModelBuilder AddMailDisplayImages(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailDisplayImages>(entity =>
        {
            entity.ToTable("mail_display_images");

            entity.HasKey(e => new { e.Tenant, e.IdUser, e.Address })
                .HasName("PRIMARY");

            entity.Property(e => e.Tenant)
                .HasColumnName("tenant")
                .HasColumnType("int(10)");

            entity.Property(e => e.IdUser)
                .HasColumnName("id_user")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");

            entity.Property(e => e.Address)
                .HasColumnName("address")
                .HasColumnType("varchar(255)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");
        });

        return modelBuilder;
    }
}
