// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ASC.Mail.Core.Dao.Entities;

public partial class MailServerMailGroup : BaseEntity
{
    public int Id { get; set; }
    public int IdTenant { get; set; }
    public int IdAddress { get; set; }
    public DateTime DateCreated { get; set; }
    public string Address { get; set; }

    public override object[] GetKeys() => new object[] { Id };
}

public static class MailServerMailGroupExtension
{
    public static ModelBuilder AddMailServerMailGroup(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailServerMailGroup>(entity =>
        {
            entity.ToTable("mail_server_mail_group");

            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .HasColumnType("int(11)")
                .ValueGeneratedOnAdd();

            entity.Property(e => e.IdTenant)
                .HasColumnName("id_tenant")
                .HasColumnType("int(11)");

            entity.Property(e => e.IdAddress)
                .HasColumnName("id_address")
                .HasColumnType("int(11)");

            entity.HasIndex(e => e.IdAddress)
                .HasDatabaseName("mail_server_address_fk_id");

            entity.HasIndex(e => e.IdTenant)
                .HasDatabaseName("tenant");

            entity.Property(e => e.DateCreated)
                .HasColumnName("date_created")
                .HasColumnType("datetime");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasColumnName("address")
                .HasColumnType("varchar(320)")
                .HasCharSet("utf8")
                .UseCollation("utf8_general_ci");
        });

        return modelBuilder;
    }
}
